# -*- coding: utf-8 -*-
"""
PlanX CartoLab — Publication Auto-Styler Engine.

Provides automatic, clean, publication-ready thematic styling for output layers
generated by CartoLab processing algorithms (choropleth, cartogram, hexbin,
dot density, proportional symbols, graticules, label points, and 2.5D massing).
"""
from __future__ import annotations

from contextlib import suppress
from typing import Optional, List, Dict

try:
    from qgis.core import (
        QgsVectorLayer,
        QgsGraduatedSymbolRenderer,
        QgsCategorizedSymbolRenderer,
        QgsSingleSymbolRenderer,
        QgsSymbol,
        QgsFillSymbol,
        QgsLineSymbol,
        QgsMarkerSymbol,
        QgsRendererRange,
        QgsColorRamp,
        QgsStyle,
        QgsPalLayerSettings,
        QgsVectorLayerSimpleLabeling,
        QgsTextFormat,
        QgsTextBufferSettings,
    )
    from qgis.PyQt.QtGui import QColor, QFont
except ImportError:
    QgsVectorLayer = QgsGraduatedSymbolRenderer = QgsCategorizedSymbolRenderer = QgsSingleSymbolRenderer = QgsSymbol = QgsFillSymbol = QgsLineSymbol = QgsMarkerSymbol = QgsRendererRange = QgsColorRamp = QgsStyle = QgsPalLayerSettings = QgsVectorLayerSimpleLabeling = QgsTextFormat = QgsTextBufferSettings = QColor = QFont = None


def auto_style_layer(
    layer: QgsVectorLayer,
    style_type: str = "choropleth",
    field_name: str = "",
    palette_name: str = "Viridis",
) -> bool:
    """
    Apply clean publication-ready default styling to a vector layer based on style_type.
    Returns True if styling was successfully applied.
    """
    if layer is None or not hasattr(layer, "geometryType"):
        return False

    st = (style_type or "").lower()
    if st == "cartogram":
        return style_cartogram_layer(layer, field_name, palette_name)
    elif st == "hexbin":
        return style_hexbin_layer(layer, field_name, palette_name)
    elif st == "dot_density":
        return style_dot_density_layer(layer)
    elif st == "proportional":
        return style_proportional_layer(layer, field_name)
    elif st == "graticule":
        return style_graticule_layer(layer)
    elif st == "labels":
        return style_label_points_layer(layer, field_name)
    elif st == "25d":
        return style_25d_layer(layer, field_name)
    else:  # default choropleth
        return style_choropleth_layer(layer, field_name, palette_name)


def style_choropleth_layer(
    layer: QgsVectorLayer,
    field_name: str = "",
    palette_name: str = "Viridis",
    classes: int = 5,
) -> bool:
    """Apply graduated color ramp with crisp 0.3pt white borders."""
    if QgsGraduatedSymbolRenderer is None or layer is None:
        return False
    if not field_name and hasattr(layer, "fields") and layer.fields().count() > 0:
        field_name = layer.fields().at(0).name()
    if not field_name:
        return False

    with suppress(Exception):
        default_style = QgsStyle.defaultStyle() if QgsStyle else None
        color_ramp = None
        if default_style:
            color_ramp = default_style.colorRamp(palette_name) or default_style.colorRamp("Viridis")

        renderer = QgsGraduatedSymbolRenderer.createRenderer(
            layer, field_name, classes,
            QgsGraduatedSymbolRenderer.Mode.Quantile,
            QgsFillSymbol.createSimple({"color": "#ffffff", "outline_color": "#ffffff", "outline_width": "0.3"}),
            color_ramp,
        )
        if renderer:
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            return True
    return False


def style_cartogram_layer(
    layer: QgsVectorLayer,
    field_name: str = "",
    palette_name: str = "Plasma",
) -> bool:
    """Apply Plasma / Magma graduated ramp to continuous cartograms."""
    return style_choropleth_layer(layer, field_name, palette_name=palette_name, classes=6)


def style_hexbin_layer(
    layer: QgsVectorLayer,
    field_name: str = "COUNT",
    palette_name: str = "Magma",
) -> bool:
    """Apply Magma graduated ramp to hexbin density cells."""
    return style_choropleth_layer(layer, field_name, palette_name=palette_name, classes=5)


def style_dot_density_layer(layer: QgsVectorLayer) -> bool:
    """Apply clean teal dots with subtle dark border."""
    if QgsSingleSymbolRenderer is None or layer is None:
        return False
    with suppress(Exception):
        symbol = QgsMarkerSymbol.createSimple({
            "color": "#1c7a75",
            "outline_color": "#132025",
            "outline_width": "0.2",
            "size": "1.8",
        })
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        layer.triggerRepaint()
        return True
    return False


def style_proportional_layer(layer: QgsVectorLayer, field_name: str = "") -> bool:
    """Apply semi-transparent copper circles with crisp outer ring."""
    if QgsSingleSymbolRenderer is None or layer is None:
        return False
    with suppress(Exception):
        symbol = QgsMarkerSymbol.createSimple({
            "color": "#b76639",
            "outline_color": "#ffffff",
            "outline_width": "0.4",
            "size": "4.0",
        })
        if hasattr(symbol, "setOpacity"):
            symbol.setOpacity(0.85)
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        layer.triggerRepaint()
        return True
    return False


def style_graticule_layer(layer: QgsVectorLayer) -> bool:
    """Apply elegant hairline slate graticule lines."""
    if QgsSingleSymbolRenderer is None or layer is None:
        return False
    with suppress(Exception):
        symbol = QgsLineSymbol.createSimple({
            "color": "#64748b",
            "width": "0.25",
            "line_style": "dash",
        })
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        layer.triggerRepaint()
        return True
    return False


def style_label_points_layer(layer: QgsVectorLayer, field_name: str = "") -> bool:
    """Apply callout point markers with white text buffer halo."""
    if QgsSingleSymbolRenderer is None or layer is None:
        return False
    with suppress(Exception):
        symbol = QgsMarkerSymbol.createSimple({
            "color": "#0284c7",
            "outline_color": "#ffffff",
            "outline_width": "0.3",
            "size": "2.5",
        })
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))

        if field_name and QgsPalLayerSettings is not None:
            settings = QgsPalLayerSettings()
            settings.fieldName = field_name
            settings.isExpression = False

            text_format = QgsTextFormat()
            if QFont and QColor:
                text_format.setFont(QFont("Segoe UI", 9, QFont.Weight.Bold))
                text_format.setColor(QColor("#0f172a"))

            buffer_settings = QgsTextBufferSettings()
            buffer_settings.setEnabled(True)
            buffer_settings.setSize(1.0)
            if QColor:
                buffer_settings.setColor(QColor("#ffffff"))
            text_format.setBuffer(buffer_settings)

            settings.setFormat(text_format)
            layer.setLabeling(QgsVectorLayerSimpleLabeling(settings))
            layer.setLabelsEnabled(True)

        layer.triggerRepaint()
        return True
    return False


def style_25d_layer(
    layer: QgsVectorLayer,
    height_field: str = "height",
    preset: str = "urban_gold",
) -> bool:
    """Apply 2.5D building extrusion styling."""
    if layer is None:
        return False
    with suppress(Exception):
        from .qgis_25d_style import apply_25d_style_to_layer, Style25DConfig
        cfg = Style25DConfig(height_field=height_field, style_preset=preset)
        return apply_25d_style_to_layer(layer, cfg)
    return False
